apiVersion: v1
kind: Service
metadata:
  name: kafka-socket-consumer-service
spec:
  selector:
    app: kafka-socket-consumer
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-socket-consumer
spec:
  selector:
    matchLabels:
      app: kafka-socket-consumer
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka-socket-consumer
    spec:
      containers:
        - name: kafka-socket-consumer
          image: 10.3.2.48:5000/kafka-socket-consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
